set_property SRC_FILE_INFO {cfile:{C:/Users/Guille/Documents/Universidad/Sexto/1er Cuatri/DSED/Entrega/DSED/Entrega/Entrega/Entrega.runs/synth_1/.Xil/Vivado-10852-LAPTOP-07004HLV/dcp5/clk_wiz_0_in_context.xdc} rfile:../dcp5/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:control/reloj} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Guille/Documents/Universidad/Sexto/1er Cuatri/DSED/Entrega/DSED/Entrega/Entrega/Entrega.runs/synth_1/.Xil/Vivado-10852-LAPTOP-07004HLV/dcp7/blk_mem_gen_0_in_context.xdc} rfile:../dcp7/blk_mem_gen_0_in_context.xdc id:2 order:EARLY scoped_inst:ram} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Guille/Documents/Universidad/Sexto/1er Cuatri/DSED/Entrega/DSED/Nexys4DDR_Master.xdc} rfile:../../../../../../../Nexys4DDR_Master.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk_100Mhz]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk_100Mhz]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells control/reloj]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins ram/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells control/reloj]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ram]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100Mhz [get_ports clk_100Mhz]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name control/reloj/clk12 -source [get_ports clk_100Mhz] -edges {1 2 3} -edge_shift {0.000 36.667 73.333} [get_pins control/reloj/clk12]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_100Mhz]
