# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.cache/wt [current_project]
set_property parent.project_path C:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/imports/Downloads/lab4_3_1.vhd
read_ip -quiet c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc]
set_property is_locked true [get_files c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci]

read_ip -quiet c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci
set_property used_in_implementation false [get_files -all c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc]
set_property is_locked true [get_files c:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/constrs_1/imports/DSED_G1/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/fpga/LCSE_Grupo12/p5/lab4_3_1/lab4_3_1.srcs/constrs_1/imports/DSED_G1/Nexys4DDR_Master.xdc]


synth_design -top lab4_3_1 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab4_3_1.dcp

catch { report_utilization -file lab4_3_1_utilization_synth.rpt -pb lab4_3_1_utilization_synth.pb }
